# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- feature/*

# pool:
# vmImage: 'ubuntu-latest'

variables:
    imgTagName: $BUILD_SOURCEBRANCHNAME

jobs:
- job: judge   
  steps:
    - script: echo $(Build.SourceBranchName)
      condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/release'))
    
    - script: |
        echo '##vso[task.setvariable variable=sauce]crushed tomatoes'
    - script: |
        echo my pipeline variable is $(sauce)

# get tag name
    - script: |
        echo $PATH
        export MY_TAGS=$(Build.SourceBranchName)
        echo $MY_TAGS
        echo $MY_TAGS | awk '{split($0,a,"-"); print a[3]}'
        export VAR=23456
        echo $VAR
        export V1=`echo $MY_TAGS`
        echo $V1
        export V2=`echo $MY_TAGS | awk '{split($0,a,"-"); print a[3]}'`
        echo $V2
        echo '##vso[task.setvariable variable=sauce]$V2'
      condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/release'))
# show?    
    - script: |
        echo $V2
        echo $(sauce)
      condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/release'))

# build docker image
    - script: echo "build image:$V2"
      condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/release'))
# ending
    - script: echo "end of job"
# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

# - script: docker build -t myredis ./5.0

# - task: ECRPushImage@1
#   inputs:
#     awsCredentials: 'DonnAWS'
#     regionName: 'us-east-1'
#     imageSource: 'imagename'
#     sourceImageName: 'myredis'
#     repositoryName: 'repo-donn-ecr'


# - task: ECRPushImage@1
#   inputs:
#     awsCredentials: 'DonnAWS'
#     regionName: 'us-east-1'
#     imageSource: 'imagename'
#     sourceImageName: 'myredis'
#     repositoryName: 'repo-donn-ecr'
#     pushTag: $(Build.SourceBranchName)

# - task: ECRPushImage@1
#   inputs:
#     awsCredentials: 'DonnAWS'
#     regionName: 'us-east-1'
#     imageSource: 'imagename'
#     sourceImageName: 'myredis'
#     repositoryName: 'repo-donn-ecr'
#     pushTag: ${env:BUILD_SOURCEBRANCHNAME}
