# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
    imgTagName: $BUILD_SOURCEBRANCHNAME
   

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: docker build -t myredis ./5.0

- task: ECRPushImage@1
  inputs:
    awsCredentials: 'DonnAWS'
    regionName: 'us-east-1'
    imageSource: 'imagename'
    sourceImageName: 'myredis'
    repositoryName: 'repo-donn-ecr'

- task: ECRPushImage@1
  inputs:
    awsCredentials: 'DonnAWS'
    regionName: 'us-east-1'
    imageSource: 'imagename'
    sourceImageName: 'myredis'
    repositoryName: 'repo-donn-ecr'
    pushTag: '$(imgTagName)'